import { db } from "@/db";
import { incidents } from "@/db/schema";

const SEED_DATA = [
  // July 2026 incidents
  { date: "2026-07-01", state: "Borno", lga: "Konduga", community: "Auno", incidentType: "terrorism", fatalities: 12, abductions: 0, injuries: 8, summary: "ISWAP fighters attacked Auno village, setting homes ablaze and killing at least 12 residents.", sourceUrl: "https://punchng.com/iswap-attacks-auno-kills-12/" },
  { date: "2026-07-02", state: "Kaduna", lga: "Chikun", community: "Guguwa", incidentType: "banditry", fatalities: 8, abductions: 15, injuries: 3, summary: "Armed bandits raided Guguwa community, killing 8 and kidnapping 15 others.", sourceUrl: "https://punchng.com/bandits-raid-guguwa/" },
  { date: "2026-07-03", state: "Niger", lga: "Shiroro", community: "Kurebe", incidentType: "clash", fatalities: 23, abductions: 0, injuries: 12, summary: "Farmer-herder clash in Kurebe left 23 dead and dozens wounded after a dispute over grazing routes.", sourceUrl: "https://premiumtimesng.com/farmer-herder-clash-shiroro/" },
  { date: "2026-07-03", state: "Benue", lga: "Guma", community: "Tse-Amande", incidentType: "clash", fatalities: 15, abductions: 0, injuries: 7, summary: "Armed herders attacked Tse-Amande community, killing 15 people in a retaliatory raid.", sourceUrl: "https://punchng.com/herders-attack-tse-amande/" },
  { date: "2026-07-04", state: "Katsina", lga: "Batsari", community: "Yanmata", incidentType: "banditry", fatalities: 6, abductions: 20, injuries: 4, summary: "Bandits stormed Yanmata village, killing 6 and abducting 20 residents including women and children.", sourceUrl: "https://dailytrust.com/bandits-storm-yanmata/" },
  { date: "2026-07-04", state: "Plateau", lga: "Barkin Ladi", community: "Ropp", incidentType: "clash", fatalities: 18, abductions: 0, injuries: 11, summary: "Communal violence erupted in Ropp community leaving 18 dead and several homes destroyed.", sourceUrl: "https://premiumtimesng.com/plateau-communal-violence/" },
  { date: "2026-07-05", state: "Zamfara", lga: "Anka", community: "Fararu", incidentType: "banditry", fatalities: 9, abductions: 30, injuries: 2, summary: "Gunmen attacked Fararu village, killing 9 and kidnapping 30 in a pre-dawn raid.", sourceUrl: "https://channelstv.com/zamfara-bandit-attack/" },
  { date: "2026-07-05", state: "Borno", lga: "Monguno", community: "Kumshe", incidentType: "terrorism", fatalities: 7, abductions: 5, injuries: 6, summary: "Boko Haram insurgents attacked Kumshe, killing 7 and taking 5 hostages.", sourceUrl: "https://punchng.com/boko-haram-attacks-kumshe/" },
  { date: "2026-07-06", state: "Kaduna", lga: "Igabi", community: "Kerawa", incidentType: "banditry", fatalities: 5, abductions: 12, injuries: 3, summary: "Bandits attacked Kerawa village, killing 5 and abducting 12.", sourceUrl: "https://dailytrust.com/bandits-attack-kerawa/" },
  { date: "2026-07-06", state: "Sokoto", lga: "Saboon Birni", community: "Goronyo", incidentType: "banditry", fatalities: 4, abductions: 8, injuries: 2, summary: "Bandits raided Goronyo area, killing 4 and kidnapping 8 residents.", sourceUrl: "https://punchng.com/sokoto-bandit-raid/" },
  { date: "2026-07-07", state: "Niger", lga: "Munya", community: "Kagara", incidentType: "banditry", fatalities: 3, abductions: 25, injuries: 0, summary: "Heavily armed bandits attacked Kagara, abducting 25 people including students.", sourceUrl: "https://channelstv.com/kagara-abduction/" },
  { date: "2026-07-07", state: "Taraba", lga: "Gassol", community: "Mutum Biyu", incidentType: "clash", fatalities: 11, abductions: 0, injuries: 9, summary: "Communal clash between Tiv and Jukun communities left 11 dead in Mutum Biyu.", sourceUrl: "https://premiumtimesng.com/taraba-communal-clash/" },
  { date: "2026-07-08", state: "Kano", lga: "Sumaila", community: "Kafin Maiyaki", incidentType: "banditry", fatalities: 2, abductions: 10, injuries: 1, summary: "Bandits attacked Kafin Maiyaki, kidnapping 10 and killing 2 who resisted.", sourceUrl: "https://dailytrust.com/kano-bandit-attack/" },
  { date: "2026-07-08", state: "Yobe", lga: "Geidam", community: "Bulabulin", incidentType: "terrorism", fatalities: 5, abductions: 3, injuries: 4, summary: "ISWAP fighters attacked Bulabulin village, killing 5 and abducting 3.", sourceUrl: "https://punchng.com/iswap-attacks-yobe/" },
  { date: "2026-07-09", state: "Plateau", lga: "Jos South", community: "Heipang", incidentType: "clash", fatalities: 8, abductions: 0, injuries: 6, summary: "Ethnic violence in Heipang left 8 dead and several homes burnt.", sourceUrl: "https://premiumtimesng.com/plateau-ethnic-violence/" },
  { date: "2026-07-09", state: "Rivers", lga: "Emohua", community: "Ogbakiri", incidentType: "armed attack", fatalities: 3, abductions: 0, injuries: 5, summary: "Cult-related violence in Ogbakiri left 3 dead and 5 wounded.", sourceUrl: "https://punchng.com/rivers-cult-violence/" },
  { date: "2026-07-10", state: "Kaduna", lga: "Kajuru", community: "Kajuru Castle area", incidentType: "banditry", fatalities: 14, abductions: 18, injuries: 7, summary: "Bandits carried out a coordinated attack in Kajuru LGA, killing 14 and kidnapping 18.", sourceUrl: "https://channelstv.com/kajuru-attack/" },
  { date: "2026-07-10", state: "Benue", lga: "Otukpo", community: "Ochobo", incidentType: "armed attack", fatalities: 4, abductions: 0, injuries: 3, summary: "Armed gunmen attacked Ochobo market, killing 4 and injuring 3.", sourceUrl: "https://dailytrust.com/benue-market-attack/" },
  { date: "2026-07-11", state: "Delta", lga: "Ughelli", community: "Eku", incidentType: "kidnapping", fatalities: 1, abductions: 6, injuries: 0, summary: "Gunmen kidnapped 6 people along Eku highway, killing 1 who tried to escape.", sourceUrl: "https://punchng.com/delta-kidnapping-highway/" },
  { date: "2026-07-11", state: "Adamawa", lga: "Hong", community: "Gulak", incidentType: "terrorism", fatalities: 6, abductions: 4, injuries: 5, summary: "Boko Haram fighters attacked Gulak, killing 6 and abducting 4.", sourceUrl: "https://premiumtimesng.com/boko-haram-adamawa/" },

  // More July incidents
  { date: "2026-07-12", state: "Zamfara", lga: "Maru", community: "Dansadau", incidentType: "banditry", fatalities: 7, abductions: 15, injuries: 3, summary: "Bandits attacked Dansadau community, killing 7 and kidnapping 15 farmers.", sourceUrl: "https://dailytrust.com/zamfara-dansadau-attack/" },
  { date: "2026-07-12", state: "Kebbi", lga: "Zuru", community: "Fakai", incidentType: "banditry", fatalities: 3, abductions: 8, injuries: 2, summary: "Armed bandits raided Fakai village, killing 3 and abducting 8.", sourceUrl: "https://punchng.com/kebbi-bandit-attack/" },
  { date: "2026-07-13", state: "Borno", lga: "Gwoza", community: "Ngoshe", incidentType: "terrorism", fatalities: 9, abductions: 2, injuries: 11, summary: "ISWAP fighters attacked Ngoshe community, killing 9 and injuring 11.", sourceUrl: "https://channelstv.com/iswap-gwoza/" },
  { date: "2026-07-13", state: "Ondo", lga: "Ose", community: "Ute", incidentType: "kidnapping", fatalities: 0, abductions: 7, injuries: 2, summary: "Gunmen kidnapped 7 farmers in Ute community, injuring 2 who resisted.", sourceUrl: "https://premiumtimesng.com/ondo-kidnapping/" },
  { date: "2026-07-14", state: "Katsina", lga: "Jibia", community: "Zabarmari", incidentType: "banditry", fatalities: 5, abductions: 12, injuries: 1, summary: "Bandits attacked Zabarmari, killing 5 and abducting 12.", sourceUrl: "https://punchng.com/katsina-jibia-attack/" },
  { date: "2026-07-14", state: "Plateau", lga: "Mangu", community: "Kombun", incidentType: "clash", fatalities: 10, abductions: 0, injuries: 8, summary: "Farmer-herder violence in Kombun left 10 dead and 8 wounded.", sourceUrl: "https://dailytrust.com/plateau-mangu-clash/" },
  { date: "2026-07-15", state: "Kaduna", lga: "Birnin Gwari", community: "Doka", incidentType: "banditry", fatalities: 11, abductions: 22, injuries: 6, summary: "Bandits attacked multiple communities in Birnin Gwari, killing 11 and kidnapping 22.", sourceUrl: "https://channelstv.com/birnin-gwari-attacks/" },
  { date: "2026-07-15", state: "Enugu", lga: "Uzo-Uwani", community: "Nkwo", incidentType: "armed attack", fatalities: 2, abductions: 5, injuries: 0, summary: "Gunmen attacked Nkwo community, killing 2 and kidnapping 5.", sourceUrl: "https://punchng.com/enugu-attack/" },
  { date: "2026-07-16", state: "Niger", lga: "Rafi", community: "Zungeru", incidentType: "banditry", fatalities: 4, abductions: 16, injuries: 2, summary: "Bandits attacked Zungeru, killing 4 and abducting 16 people.", sourceUrl: "https://premiumtimesng.com/niger-zungeru-attack/" },
  { date: "2026-07-16", state: "Taraba", lga: "Wukari", community: "Sarki Kudu", incidentType: "clash", fatalities: 6, abductions: 0, injuries: 4, summary: "Communal violence in Wukari left 6 dead and dozens displaced.", sourceUrl: "https://dailytrust.com/taraba-wukari-clash/" },
  { date: "2026-07-17", state: "Borno", lga: "Mafa", community: "Mafa town", incidentType: "terrorism", fatalities: 4, abductions: 0, injuries: 8, summary: "Suicide bomber attacked a market in Mafa, killing 4 and injuring 8.", sourceUrl: "https://channelstv.com/borno-market-bombing/" },
  { date: "2026-07-17", state: "Oyo", lga: "Ibarapa", community: "Igangan", incidentType: "kidnapping", fatalities: 1, abductions: 4, injuries: 0, summary: "Gunmen kidnapped 4 people in Igangan, killing 1 during the abduction.", sourceUrl: "https://punchng.com/oyo-kidnapping-igangan/" },
  { date: "2026-07-18", state: "Sokoto", lga: "Isa", community: "Tozai", incidentType: "banditry", fatalities: 8, abductions: 10, injuries: 3, summary: "Bandits attacked Tozai village in Isa LGA, killing 8 and kidnapping 10.", sourceUrl: "https://dailytrust.com/sokoto-isa-attack/" },
  { date: "2026-07-18", state: "Benue", lga: "Gwer West", community: "Naka", incidentType: "clash", fatalities: 7, abductions: 0, injuries: 5, summary: "Armed herdsmen attacked Naka community, killing 7 and razing homes.", sourceUrl: "https://premiumtimesng.com/benue-herders-attack/" },
  { date: "2026-07-19", state: "Kaduna", lga: "Zangon Kataf", community: "Zangon Kataf", incidentType: "clash", fatalities: 5, abductions: 0, injuries: 3, summary: "Ethnic violence in Zangon Kataf left 5 dead.", sourceUrl: "https://channelstv.com/zangon-kataf-violence/" },
  { date: "2026-07-19", state: "FCT", lga: "Kwali", community: "Yebu", incidentType: "kidnapping", fatalities: 2, abductions: 9, injuries: 0, summary: "Gunmen abducted 9 people from Yebu community, killing 2 who resisted.", sourceUrl: "https://punchng.com/fct-kidnapping-kwali/" },
  { date: "2026-07-20", state: "Borno", lga: "Damboa", community: "Chibok", incidentType: "terrorism", fatalities: 15, abductions: 8, injuries: 10, summary: "Boko Haram attacked communities near Chibok, killing 15 and abducting 8.", sourceUrl: "https://premiumtimesng.com/chibok-attack-2026/" },
  { date: "2026-07-20", state: "Katsina", lga: "Safana", community: "Yantumaki", incidentType: "banditry", fatalities: 3, abductions: 11, injuries: 1, summary: "Bandits attacked Yantumaki, killing 3 and kidnapping 11.", sourceUrl: "https://dailytrust.com/katsina-safana-attack/" },

  // August 2026 incidents
  { date: "2026-08-01", state: "Kaduna", lga: "Giwa", community: "Fatika", incidentType: "banditry", fatalities: 6, abductions: 14, injuries: 4, summary: "Bandits attacked Fatika community, killing 6 and kidnapping 14 residents.", sourceUrl: "https://punchng.com/kaduna-fatika-attack/" },
  { date: "2026-08-02", state: "Plateau", lga: "Bokkos", community: "Bokkos town", incidentType: "clash", fatalities: 22, abductions: 0, injuries: 15, summary: "Coordinated attacks on Bokkos community left 22 dead and many wounded.", sourceUrl: "https://premiumtimesng.com/plateau-bokkos-attack/" },
  { date: "2026-08-02", state: "Borno", lga: "Chibok", community: "Askira", incidentType: "terrorism", fatalities: 8, abductions: 3, injuries: 7, summary: "ISWAP fighters attacked Askira, killing 8 and taking 3 hostages.", sourceUrl: "https://channelstv.com/borno-askira-attack/" },
  { date: "2026-08-03", state: "Niger", lga: "Shiroro", community: "Lakpma", incidentType: "banditry", fatalities: 10, abductions: 20, injuries: 5, summary: "Bandits carried out mass abduction in Lakpma, killing 10 and kidnapping 20.", sourceUrl: "https://dailytrust.com/niger-shiroro-abduction/" },
  { date: "2026-08-03", state: "Benue", lga: "Logo", community: "Ukum", incidentType: "clash", fatalities: 13, abductions: 0, injuries: 8, summary: "Farmer-herder clash in Ukum left 13 dead and multiple homes destroyed.", sourceUrl: "https://punchng.com/benue-ukum-clash/" },
  { date: "2026-08-04", state: "Zamfara", lga: "Tsafe", community: "Kizara", incidentType: "banditry", fatalities: 5, abductions: 18, injuries: 2, summary: "Bandits attacked Kizara, killing 5 and abducting 18 people.", sourceUrl: "https://premiumtimesng.com/zamfara-kizara-attack/" },
  { date: "2026-08-04", state: "Kano", lga: "Doguwa", community: "Kogin Wurma", incidentType: "clash", fatalities: 9, abductions: 0, injuries: 6, summary: "Communal violence in Doguwa left 9 dead after a land dispute.", sourceUrl: "https://channelstv.com/kano-doguwa-clash/" },
  { date: "2026-08-05", state: "Katsina", lga: "Kurfi", community: "Runka", incidentType: "banditry", fatalities: 4, abductions: 7, injuries: 1, summary: "Bandits raided Runka village, killing 4 and kidnapping 7.", sourceUrl: "https://dailytrust.com/katsina-kurfi-attack/" },
  { date: "2026-08-05", state: "Rivers", lga: "Ogba/Egbema/Ndoni", community: "Obrikom", incidentType: "armed attack", fatalities: 2, abductions: 3, injuries: 4, summary: "Cult-related violence in Obrikom left 2 dead, 3 abducted and 4 injured.", sourceUrl: "https://punchng.com/rivers-cult-attack/" },
  { date: "2026-08-06", state: "Borno", lga: "Ngala", community: "Gamboru", incidentType: "terrorism", fatalities: 11, abductions: 6, injuries: 9, summary: "ISWAP fighters attacked Gamboru border town, killing 11 and abducting 6.", sourceUrl: "https://premiumtimesng.com/gamboru-iswap-attack/" },
  { date: "2026-08-06", state: "Kaduna", lga: "Soba", community: "Maigirya", incidentType: "banditry", fatalities: 3, abductions: 9, injuries: 0, summary: "Bandits attacked Maigirya, kidnapping 9 people and killing 3.", sourceUrl: "https://channelstv.com/kaduna-soba-attack/" },
  { date: "2026-08-07", state: "Adamawa", lga: "Michika", community: "Bazza", incidentType: "terrorism", fatalities: 7, abductions: 0, injuries: 12, summary: "Boko Haram attacked Bazza, killing 7 and wounding 12.", sourceUrl: "https://dailytrust.com/adamawa-bazza-attack/" },
  { date: "2026-08-07", state: "Ogun", lga: "Yewa North", community: "Iselu", incidentType: "kidnapping", fatalities: 0, abductions: 5, injuries: 1, summary: "Gunmen kidnapped 5 people along Iselu road, injuring 1.", sourceUrl: "https://punchng.com/ogun-kidnapping/" },
  { date: "2026-08-08", state: "Plateau", lga: "Wase", community: "Kadarko", incidentType: "clash", fatalities: 16, abductions: 0, injuries: 10, summary: "Farmer-herder clash in Kadarko left 16 dead and many displaced.", sourceUrl: "https://premiumtimesng.com/plateau-wase-clash/" },
  { date: "2026-08-08", state: "Sokoto", lga: "Tangaza", community: "Gudu", incidentType: "banditry", fatalities: 6, abductions: 14, injuries: 3, summary: "Bandits attacked Gudu community, killing 6 and kidnapping 14.", sourceUrl: "https://channelstv.com/sokoto-tangaza-attack/" },
  { date: "2026-08-09", state: "Yobe", lga: "Gujba", community: "Gujba town", incidentType: "terrorism", fatalities: 3, abductions: 4, injuries: 2, summary: "Insurgents attacked Gujba, killing 3 and taking 4 hostages.", sourceUrl: "https://dailytrust.com/yobe-gujba-attack/" },
  { date: "2026-08-09", state: "Niger", lga: "Borgu", community: "Wawa", incidentType: "banditry", fatalities: 2, abductions: 11, injuries: 0, summary: "Bandits kidnapped 11 people from Wawa community.", sourceUrl: "https://punchng.com/niger-borgu-kidnapping/" },
  { date: "2026-08-10", state: "Kaduna", lga: "Chikun", community: "Gwagwada", incidentType: "banditry", fatalities: 4, abductions: 16, injuries: 2, summary: "Bandits attacked Gwagwada, killing 4 and kidnapping 16.", sourceUrl: "https://premiumtimesng.com/kaduna-gwagwada-attack/" },
  { date: "2026-08-10", state: "FCT", lga: "Bwari", community: "Dutse", incidentType: "kidnapping", fatalities: 1, abductions: 6, injuries: 0, summary: "Gunmen abducted 6 people from Dutse community, killing 1.", sourceUrl: "https://channelstv.com/fct-dutse-kidnapping/" },

  // A few more recent
  { date: "2026-08-11", state: "Kebbi", lga: "Bagudo", community: "Kende", incidentType: "banditry", fatalities: 5, abductions: 9, injuries: 2, summary: "Bandits attacked Kende village, killing 5 and kidnapping 9.", sourceUrl: "https://dailytrust.com/kebbi-bagudo-attack/" },
  { date: "2026-08-11", state: "Benue", lga: "Agatu", community: "Odugbo", incidentType: "clash", fatalities: 8, abductions: 0, injuries: 6, summary: "Herdsmen attacked Odugbo community, killing 8.", sourceUrl: "https://punchng.com/benue-agatu-attack/" },
  { date: "2026-08-12", state: "Borno", lga: "Kala/Balge", community: "Rann", incidentType: "terrorism", fatalities: 6, abductions: 2, injuries: 4, summary: "ISWAP fighters attacked Rann, killing 6 and taking 2 hostages.", sourceUrl: "https://premiumtimesng.com/borno-rann-attack/" },
  { date: "2026-08-12", state: "Katsina", lga: "Dutsin Ma", community: "Kuturu", incidentType: "banditry", fatalities: 3, abductions: 8, injuries: 1, summary: "Bandits attacked Kuturu, killing 3 and kidnapping 8.", sourceUrl: "https://channelstv.com/katsina-dutsinma-attack/" },
  { date: "2026-08-13", state: "Zamfara", lga: "Gusau", community: "Damba", incidentType: "banditry", fatalities: 7, abductions: 13, injuries: 3, summary: "Bandits raided Damba, killing 7 and abducting 13.", sourceUrl: "https://dailytrust.com/zamfara-gusau-raid/" },
  { date: "2026-08-13", state: "Delta", lga: "Isoko South", community: "Oleh", incidentType: "kidnapping", fatalities: 0, abductions: 4, injuries: 2, summary: "Gunmen kidnapped 4 people in Oleh community, injuring 2 during the abduction.", sourceUrl: "https://punchng.com/delta-oleh-kidnapping/" },
  { date: "2026-08-14", state: "Kaduna", lga: "Kubau", community: "Anchau", incidentType: "banditry", fatalities: 5, abductions: 11, injuries: 0, summary: "Bandits attacked Anchau, killing 5 and abducting 11.", sourceUrl: "https://premiumtimesng.com/kaduna-anchau-attack/" },
  { date: "2026-08-14", state: "Plateau", lga: "Barkin Ladi", community: "Heipang", incidentType: "clash", fatalities: 12, abductions: 0, injuries: 9, summary: "Fresh communal violence in Heipang left 12 dead and dozens displaced.", sourceUrl: "https://channelstv.com/plateau-heipang-violence/" },
  { date: "2026-08-15", state: "Borno", lga: "Abadam", community: "Malam Fatori", incidentType: "terrorism", fatalities: 10, abductions: 5, injuries: 8, summary: "ISWAP attacked Malam Fatori border town, killing 10 and abducting 5.", sourceUrl: "https://dailytrust.com/borno-malam-fatori/" },
  { date: "2026-08-15", state: "Imo", lga: "Orsu", community: "Orsu Ihitteukwa", incidentType: "armed attack", fatalities: 4, abductions: 0, injuries: 3, summary: "Unknown gunmen attacked Orsu community, killing 4 and injuring 3.", sourceUrl: "https://punchng.com/imo-attack-orsu/" },
];

async function seed() {
  console.log("Seeding incidents...");

  for (const incident of SEED_DATA) {
    try {
      await db.insert(incidents).values({
        ...incident,
        contentFp: null,
        semanticFp: `${incident.date}-${incident.state}-${incident.lga}-${incident.incidentType}-${incident.fatalities}-${incident.abductions}`,
      }).onConflictDoNothing();
    } catch (e) {
      console.error(`Failed to insert incident: ${incident.date} ${incident.state}`, e);
    }
  }

  console.log(`Seeded ${SEED_DATA.length} incidents.`);
}

seed().catch(console.error);
